<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0-windows7.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<Platforms>x64</Platforms>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<ImplicitUsings>disable</ImplicitUsings>
		<RootNamespace>GPM.CustomAnalyses</RootNamespace>
		<AssemblyName>GPM.CustomAnalyses</AssemblyName>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<EnableDynamicLoading>true</EnableDynamicLoading>
		<RuntimeIdentifier>win10-x64</RuntimeIdentifier>
		<SelfContained>false</SelfContained>
	</PropertyGroup>

	<PropertyGroup Label="Direct Output" Condition="'$(Configuration)' == 'Debug'">
		<OutputPath>$(LOCALAPPDATA)\CAMECA\AP Suite\Extensions\$(AssemblyName)</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>

	<PropertyGroup Label="Package">
		<Title>GPM.CustomAnalyses</Title>
		<Authors>Groupe de Physique des Matériaux,CAMECA Instruments Inc.</Authors>
		<Company>CAMECA Instruments, Inc.</Company>
		<Product>AP Suite</Product>
		<Description>Custom analysis for isoposition filtering</Description>
		<Copyright>Copyright 2022 © Groupe de Physique des Matériaux and CAMECA Instruments Inc. All rights reserved.</Copyright>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<IncludeBuildOutput>true</IncludeBuildOutput>
		<NuspecFile>GPM.CustomAnalyses.nuspec</NuspecFile>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Examples\ExampleAnalysis\PieChartIcon.png" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Cameca.CustomAnalysis.Utilities" Version="3.7.0" />
		<PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
	</ItemGroup>
	
	<ItemGroup>
	  <Resource Include="Images\PieChartIcon.png" />
	</ItemGroup>
	
	<ItemGroup>
	  <None Update="Help.Custom analysis doc 250225.docx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<!-- Nuspec Initiaization and Configuration -->
	<Target Name="InitializeStandardNuspecProperties" BeforeTargets="GenerateNuspec" Condition="'$(IsPackable)' == 'true'">
		<PropertyGroup Condition="'$(NuspecFile)' != '' and '$(NuspecProperties)' == ''">
			<NuspecProperties>
				id=$(AssemblyName);
				version=$(Version);
				authors=$(Authors);
				description=$(Description);
				title=$(Title);
				copyright=$(Copyright);
				repoType=$(RepositoryType);
				repoUrl=$(RepositoryUrl);
				projectUrl=$(RepositoryUrl);
				repoCommit=$(RepositoryCommit);
				tfw=$(TargetFramework);
				outDir=$(MSBuildThisFileDirectory)$(OutputPath)
			</NuspecProperties>
		</PropertyGroup>
	</Target>
</Project>
